function PlotSolution(tour,model,r)

    %tour=[tour tour(1)];
    
   % if r<8
    %    color=r;
    
   % else
      %  color=randi([1 7]);
    %end
    
    if r>12
        
       color=mod(r,10);
    else
        color=r;
    end
    
    
    
    hold on
    
    if color==1
      
        plot(model.x(tour),model.y(tour),...
             'Color','b',...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','c',...
             'MarkerFaceColor','b',...
             'LineWidth',1.5);
         hold on
      
    elseif color==2
        plot(model.x(tour),model.y(tour),...
             'Color','m',...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','r',...
             'MarkerFaceColor','m',...
             'LineWidth',1.5);
         hold on
            
    elseif color==3
        plot(model.x(tour),model.y(tour),...
             'Color','c',...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','b',...
             'MarkerFaceColor','c',...
             'LineWidth',1.5);
         hold on
    
    elseif color==4
        plot(model.x(tour),model.y(tour),...
             'Color','r',...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','m',...
             'MarkerFaceColor','r',...
             'LineWidth',1.5);
         hold on
        
    elseif color==5
        plot(model.x(tour),model.y(tour),...
             'Color','k',...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','b',...
             'MarkerFaceColor','k',...
             'LineWidth',1.5);
         hold on
        
    elseif color==6
        plot(model.x(tour),model.y(tour),...
             'Color','g',...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','k',...
             'MarkerFaceColor','g',...
             'LineWidth',1.5);
         hold on
        
    elseif color==7
        plot(model.x(tour),model.y(tour),...
             'Color',[0.9412 0.4706 0],...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','k',...
             'MarkerFaceColor',[0.9412 0.4706 0],...
             'LineWidth',1.5);
         hold on
    
    elseif color==8
        plot(model.x(tour),model.y(tour),...
             'Color',[1 0.502 0.502],...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','g',...
             'MarkerFaceColor',[1 0.502 0.502],...
             'LineWidth',1.5);
         hold on
    elseif color==9
        plot(model.x(tour),model.y(tour),...
             'Color',[0 0.502 0.502],...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','b',...
             'MarkerFaceColor',[0 0.502 0.502],...
             'LineWidth',1.5);
         hold on
    elseif color==10
        plot(model.x(tour),model.y(tour),...
             'Color',[0.251 0 0.502],...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','m',...
             'MarkerFaceColor',[0.251 0 0.502],...
             'LineWidth',1.5);
         hold on
    elseif color==11
        plot(model.x(tour),model.y(tour),...
             'Color',[0 0.251 0],...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','g',...
             'MarkerFaceColor',[0 0.251 0],...
             'LineWidth',1.5);
         hold on
    elseif color==12
        plot(model.x(tour),model.y(tour),...
             'Color',[0.502 0 0],...
             'Marker','o',...
             'MarkerSize',10,...
             'MarkerEdgeColor','g',...
             'MarkerFaceColor',[0.502 0 0],...
             'LineWidth',1.5);
         hold on
         
         
 
    end
    hold on
   
     

            
    
 
    
    
end